[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_THEME = "repo"
  HUGO_THEMESDIR = "/opt/build"
  HUGO_VERSION = "0.92.1"

[context.production.environment]
  HUGO_VERSION = "0.92.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  HUGO_BASEURL = "https://oeyoews.netlify.app/"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.92.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.92.1"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.92.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

#[[redirects]]
#from = "/npmjs/*"
#to = "/npmjs/"
#status = 200
